### ISSUE TITLE
Error when trying to run gramine docker container in SGX

### ISSUE THREAD

**Issue by Mikerah** [amiller/gramine-rsademo#2]
When running `docker compose run --rm gramine gramine-sgx python`, I get the following error on my system:
```
WARN[0000] /home/mikerah/Documents/HashCloak/Projects/gramine-rsademo/docker-compose.yml: `version` is obsolete 
Error response from daemon: error gathering device information while adding custom device "/dev/sgx_enclave": no such file or directory
```

Am I missing an option to instance or is it potentially because my machine doesn't have SGX?

**Comment by amiller** [comment]
yes this is an indicator that sgx is not available, or the bios is not enabled, and the kernel version is not enabled 
 https://gramine.readthedocs.io/en/stable/manpages/is-sgx-available.html

**Comment by Mikerah** [comment]
Thanks
